src/main/java/com/book_everywhere/web/dto/image/ImageDto.java
디렉토리 설정 중 dto가 누락되어 class 추가 후 merge합니다
=> chore : 디렉토리 설정 추가.

src/main/java/com/book_everywhere/domain/image/Image.java, src/main/java/com/book_everywhere/domain/pin/Pin.java, src/main/java/com/book_everywhere/domain/review/Review.java, src/main/java/com/book_everywhere/domain/visit/Visit.java, src/main/java/com/book_everywhere/web/AuthController.java, src/main/java/com/book_everywhere/web/UserController.java, src/main/java/com/book_everywhere/web/dto/pin/PinDto.java, src/main/resources/templates/home.html, src/main/resources/templates/login.html
=> chore: Entity 업데이트 및 수정!

src/main/java/com/book_everywhere/DummyDataGenerator.java, src/main/java/com/book_everywhere/config/SecurityConfig.java, src/main/java/com/book_everywhere/config/auth/CustomOAuth2UserService.java, src/main/java/com/book_everywhere/domain/book/BookRepository.java, src/main/java/com/book_everywhere/service/BookService.java, src/main/java/com/book_everywhere/service/PinService.java, src/main/java/com/book_everywhere/service/ReviewService.java, src/main/java/com/book_everywhere/service/TagService.java, src/main/java/com/book_everywhere/service/VisitService.java, src/main/java/com/book_everywhere/web/AuthController.java, src/main/java/com/book_everywhere/web/PinController.java, src/main/java/com/book_everywhere/web/ReviewController.java, src/main/resources/application.yml
독후감등록에 따른 기능테스트가 완료되었습니다.
"fix : visited, tagge , review.book이 업데이트 안되던 버그를 수정하였습니다."  
- 독후감(review)등록 기능
- 독후감등록에 따른 핀 생성기능,  (최초/중복)에 따른 분기처리가 완료되었습니다.
- 독후감등록에 따른 책 생성기능,  (최초/중복)에 따른 분기처리가 완료되었습니다.
- 독후감등록에 따른 태그 등록기능, (최초/중복)에 따른 (Tagged) 분기처리가 완료되었습니다.
- 독후감등록에 따른 방문 등록기능,  (최초/중복)에 따른 (Visited) 분기처리가 완료되었습니다.
- 독후감 생성기능(review)이 완료되었습니다.
1. tagService에 아래와 같은 반복문이 추가되었습니다. tag에 갯수에 따라 존재하지 않는태그만 추가해줍니다.
for (String content : reviewRespDto.getTags()) {};
2. review등록에 따른 Dto가 추가되었습니다.
- ReviewRespDto
- PinRespDto
- BookRespDto
아래와 같은 JSON폼을 통하여 review등록 기능 테스트를 완료하였습니다.
{
"socialId" : 3345007590,
"title": "titleInfo",
"isPrivate": true,
"pinRespDto": {
"name": "placeInfo.place_name",
"y": 488532.02,
"x": 100809.02,
"address": "placeInfo.road_address_name",
"isPrivate": false
}, …
=> feat/test: 독후감 등록에 따른 핀,책, 태그,방문등록 기능이 구현 완료되었습니다.

src/main/java/com/book_everywhere/domain/book/Book.java, src/main/java/com/book_everywhere/service/BookService.java, src/main/java/com/book_everywhere/service/ReviewService.java, src/main/java/com/book_everywhere/service/TagService.java
Book userBook = bookRepository.mFindBookByUserIdAndTitle(user.getId(), bookRespDto.getTitle());
->
Book userBook = bookRepository.mFindBookByUserIdAndTitle(user.getSocialId(), bookRespDto.getTitle());
유저가 이미 등록한 book을 못찾는 오류를 해결했습니다.
=> fix : book notFound 해결.

src/main/java/com/book_everywhere/domain/tagged/Tagged.java, src/main/java/com/book_everywhere/service/TagService.java, src/main/java/com/book_everywhere/web/dto/tag/TagRespDto.java
RespDto의 구성이 변경됨에 따른 수정이 있었습니다.
Postman Test를 완료하였습니다.
=> chore : RespDto 구성 변경에 따른 수정.

src/main/java/com/book_everywhere/domain/tagged/TaggedRepository.java, src/main/java/com/book_everywhere/service/TagService.java, src/main/java/com/book_everywhere/web/TagController.java
모든 핀의 상위 5개의 태그를 전달해주는 api 구현완료했습니다.
변경 file
- TaggedRepository
- TagService
- TagController
=> feat: 핀의 상위 5개의 태그를 전달해주는 api 구현

Dockerfile, src/main/java/com/book_everywhere/DummyDataGenerator.java, src/main/java/com/book_everywhere/web/AuthController.java, src/main/java/com/book_everywhere/web/BookController.java, src/main/java/com/book_everywhere/web/PinController.java, src/main/java/com/book_everywhere/web/ReviewController.java, src/main/resources/META-INF/MANIFEST.MF
fix: AuthController의 index 메소드 오류 발생으로 삭제 및 /api 주소 매핑
=> fix: AuthController의 index 메소드 오류 발생으로 삭제 및 /api 주소 매핑

src/main/java/com/book_everywhere/web/UniversalController.java
feat :  로드벨런서 health check를 위한 UniversalController가 추가되었습니다.
=> feat :  로드벨런서 health check를 위한 UniversalController가 추가되었습니다.

src/main/java/com/book_everywhere/web/AuthController.java, src/main/java/com/book_everywhere/web/PinController.java, src/main/java/com/book_everywhere/web/ReviewController.java
마지막 기능 구현이 완료되었습니다.
feat : 독후감 수정기능에 따른 단일독후감 조회 및 독후감 업데이트 기능 구현
=> feat : 독후감 수정기능에 따른 단일독후감 조회 및 독후감 업데이트 기능 구현

src/main/java/com/book_everywhere/config/SecurityConfig.java, src/main/java/com/book_everywhere/domain/pin/Pin.java, src/main/java/com/book_everywhere/domain/review/Review.java, src/main/java/com/book_everywhere/service/PinService.java, src/main/java/com/book_everywhere/service/ReviewService.java, src/main/java/com/book_everywhere/web/ReviewController.java, src/main/java/com/book_everywhere/web/dto/pin/PinDto.java, src/main/java/com/book_everywhere/web/dto/pin/PinRespDto.java, src/main/java/com/book_everywhere/web/dto/review/ReviewDto.java, src/main/java/com/book_everywhere/web/dto/review/ReviewRespDto.java
feat: CORS 설정 수정 및 모든 리뷰 조회 기능 수정
=> feat: CORS 설정 수정 및 모든 리뷰 조회 기능 수정

Dockerfile, build.gradle, src/main/java/com/book_everywhere/config/SecurityConfig.java, src/main/java/com/book_everywhere/domain/review/Review.java, src/main/java/com/book_everywhere/service/ReviewService.java, src/main/java/com/book_everywhere/service/TagService.java, src/main/java/com/book_everywhere/service/VisitService.java, src/main/java/com/book_everywhere/web/ReviewController.java, src/main/java/com/book_everywhere/web/UniversalController.java, src/main/java/com/book_everywhere/web/dto/review/ReviewDto.java, src/main/resources/application.yml
=> refactor: CICD로 인한 구조 변경

src/main/resources/application.yml
=> fix : CICD를 위한 yml파일 수정

src/main/java/com/book_everywhere/domain/visit/VisitRepository.java, src/main/java/com/book_everywhere/service/WebDataService.java, src/main/java/com/book_everywhere/web/WebDataController.java
tagService -> tagRepository로 변경
WebDataController
@Slfj4 삭제
VisitRepository
@Repository 어노테이션 추가
=> chore: WebDataContorller,Service 수정

src/main/java/com/book_everywhere/service/DataService.java, src/main/java/com/book_everywhere/service/ReviewService.java, src/main/java/com/book_everywhere/service/TagService.java, src/main/java/com/book_everywhere/service/WebDataService.java, src/main/java/com/book_everywhere/web/DataController.java, src/main/java/com/book_everywhere/web/ReviewController.java
ReviewController
세분화한 독후감 조회 기능에서 오류가 발생했습니다.
PageNation 오류 해결
=> fix : WebConfiguration Bean 생성 불가 오류 해결

src/main/java/com/book_everywhere/domain/book/Book.java, src/main/java/com/book_everywhere/service/DataService.java, src/main/java/com/book_everywhere/web/DataController.java, src/main/java/com/book_everywhere/web/dto/AllDataDto.java, src/main/java/com/book_everywhere/web/dto/book/BookRespDto.java
ReviewRespDto의 스펙 변경 요청이 있어
ReviewRespDto 대신 AllDataDto로 변경합니다
추가된 데이터
bookRespDto
author
AllDataDto
createAt - review기준
=> chore: ReviewRespDto -> AllDataDto로 변경

Dockerfile, src/main/java/com/book_everywhere/web/UniversalController.java, src/main/resources/application.yml
=> test : 8082포트 테스트

src/main/java/com/book_everywhere/service/DataService.java
DataService 변경
tagRespDto에 isSelected가 true인 값만 가져오는 오류를 수정했습니다.
=> fix : /api/data/all 조회시 tag의 isSelected가 true인 값만 가져오는 오류를 수정했습니다.

src/main/java/com/book_everywhere/domain/pin/Pin.java, src/main/java/com/book_everywhere/web/dto/pin/PinDto.java, src/main/java/com/book_everywhere/web/dto/pin/PinRespDto.java
placeId의 변수 타입을 double로 변경했습니다
=> chore : placeId Long -> double로 변경

src/main/java/com/book_everywhere/domain/visit/Visit.java, src/main/java/com/book_everywhere/service/DataService.java, src/main/java/com/book_everywhere/service/VisitService.java
임시적으로 장소의 개인/공유 를 선택하도록 변경했습니다
=> fix : pinRespDto의 isPrivate가 Visit 객체에 저장되도록 변

src/main/java/com/book_everywhere/service/DataService.java
=> fix: userId 오류 테스트

.github/workflows/CICD.yml, src/main/java/com/book_everywhere/domain/category/Category.java, src/main/java/com/book_everywhere/domain/category/CategoryRepository.java, src/main/java/com/book_everywhere/domain/tag/Tag.java, src/main/java/com/book_everywhere/domain/tagged/TaggedRepository.java, src/main/java/com/book_everywhere/service/DataService.java, src/main/java/com/book_everywhere/service/PinService.java, src/main/java/com/book_everywhere/web/DataController.java, src/main/java/com/book_everywhere/web/PinController.java, src/main/java/com/book_everywhere/web/dto/pin/PinWithTagCountRespDto.java, src/main/java/com/book_everywhere/web/dto/tag/TagCountRespDto.java, src/main/java/com/book_everywhere/web/dto/tag/TagRespDto.java
category 테이블을 추가했습니다
column : id, name
DataService에 category 조회가 추가되었습니다.
모든 핀의 상위 5개 태그 개수와 함께 조회 하는 기능이 구현되었습니다.
PinWithTagCountRespDto가 추가되었습니다.
TagCountRespDto가 추가되었습니다.
PinController에 /api/map/tag/count 가 추가되었습니다.
pinService에 핀의상위5개태그개수와함께조회 매소드가추가되었습니다.
TaggedRepository에 mFindPinWithTagCount 매소드가추가되었습니다.
프론트 단에서 기록하기 페이지의 태그 부분에 대해서 새롭게 만들어 주시면 테스트를 진행할 예정입니다.
=> BookEveryWhere Backend Sever version.1.1

src/main/java/com/book_everywhere/service/TagService.java, src/main/java/com/book_everywhere/web/dto/review/ReviewRespDto.java
TagRespDto -> String 배열로 변경하였습니다.
=> chore : 태그등록 서비스 변경

build.gradle, src/main/java/com/book_everywhere/config/SwaggerConfig.java, src/main/java/com/book_everywhere/web/ReviewController.java, src/main/java/com/book_everywhere/web/UniversalController.java
API 문서화 기능을 위한 Swagger 의존성을 추가하였습니다.
=> feat : API 문서화 기능 추가 (Swagger)

src/main/resources/application.yml
=> fix : Swagger HTTPS리다이렉트 설정
